export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SET_FEEDBACK_ALERT = "SET_FEEDBACK_ALERT";
export const REMOVE_FEEDBACK_ALERT = "REMOVE_FEEDBACK_ALERT";
